### ISSUE TITLE
Drop-in replacement of react-facebook-login?

### ISSUE THREAD

**Issue by jpvg10** [greatSumini/react-facebook-login#334]
Is this package a drop-in replacement for [react-facebook-login](https://github.com/keppelen/react-facebook-login)? Can I use it without having to make any changes to my code?

By the way, the [documentation](https://sumini.dev/react-facebook-login/?path=/story/overview-introduction--page) page appears blank for me...

Thanks!

**Comment by greatSumini** [comment]
@jpvg10 
There is no big difference because this package use the same sdk with [react-facebook-login](https://github.com/keppelen/react-facebook-login).
But you might needs some trivail updates(e.g. prop name, ...) you can check documentation [here](https://github.com/greatSumini/react-facebook-login/blob/master/docs/0-overview/0-0_introduction.stories.mdx)

thanks for using and error report! 🙇🏻

**Comment by jpvg10** [comment]
Perfect, thank you!
